spring:
  application:
    name: employee-ws
  datasource:
    url: jdbc:mysql://employee-db:3306/employeedb
    username: user
    password: password

server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8011/eureka/
      
jwt:
  secret: secret