apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: employee-service
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: employee-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/back-end: "true"
        io.kompose.service: employee-service
    spec:
      containers:
        - image: icr.io/fscc-namespace/employee-service@sha256:d5e8270fae137dd4951960c9866cc4eff3467eec2e958486a8d7c05a1261b953
          name: employee-service
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
      tolerations:
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoSchedule"
status: {}
